const ADD_LOCATION = 'ADD_LOCATION';
const ADD_MY_LOCATION = 'ADD_MY_LOCATION';
const ADD_ROUTE = 'ADD_ROUTE';
const ADD_PICTURE = 'ADD_PICTURE';
const RESET_LOCATION = 'RESET_LOCATION';

export default {
    ADD_LOCATION,
    ADD_MY_LOCATION,
    ADD_ROUTE,
    ADD_PICTURE,
    RESET_LOCATION,
}